##################################################################
# Configuration file:
# 
# This file contains the configuration parameters for running FINDER. 
# The input and output files are specified here as well
# as additional flags that are used by FINDER for debugging and
# reporting.
#
# @author Haneen Dabain
# @email  haneend@cse.yorku.ca
# @date   January 2011


##################################################################
# Input files
##################################################################


input.design.patterns.xml.file = $PROJCONFIG_DIR/designpatterns.xml

# Please specify the software system configuration file here.
input.software.xml.file        = $PROJCONFIG_DIR/software.xml

# Please specify the scripts configuration file here.
input.scripts.xml.file	   = $PROJCONFIG_DIR/scripts.xml


##################################################################
# Output files
##################################################################

output.exception.txt.file = $PROJCONFIG_DIR/errInfo/exception.txt

